### ISSUE TITLE
Add ability to customize number of top-K detections for object detection saliency

### ISSUE THREAD

**Issue by brianhhu** [XAITK/xaitk-saliency-web-demo#13]
Similar to image classification saliency (which exposes an option for the number of top-K classes to explain), the object detection saliency GUI could have a similar dropdown for customizing the number of top-K detections to compute saliency for. This would make the context between the two tasks more similar for a user.

**Comment by jourdain** [comment]
I've added in the xai param section, but I can reuse the one it the toolbar too.
