### ISSUE TITLE
Updating code dependencies?

### ISSUE THREAD

**Issue by jourdain** [XAITK/xaitk-saliency-web-demo#15]
```python
    altair==4.1.0
    smqtk-classifier==0.19.0
    smqtk-core==0.18.1
    smqtk-dataprovider==0.16.0
    smqtk-descriptors==0.18.1
    smqtk-detection[torch,centernet]==0.19.0
    smqtk-image-io==0.16.2
    xaitk-saliency==0.6.1
    torchvision==0.11.2
    scikit-learn==0.24.2
    scikit-image==0.18.3
    ubelt==1.1.1
```

@Purg @brianhhu Any suggestion in term of version if we should update any of the listed above?

**Comment by jourdain** [comment]
Actually I was trying to start from scratch and I can't seem to install it properly on linux following the readme. 
It is also failing on mac M1 but much sooner.

I was doing the following

```bash
conda create --name xaitk python=3.9 -y
conda activate xaitk

# Try to add but did not solved the error
conda install numba

pip install -e .

xaitk-saliency-demo
``` 

Any suggestion on how to properly install all the packages?

**Comment by Purg** [comment]
Sorry, are you asking for advise on the versions of the above packages to use? I can refer you to a list of what the locked versions of `xaitk-saliency`'s deps are if that would help.

FWIW, I just created a new env for this repo and followed the README and resulted in a successful `pip install -e .` I'm not sure what issue you are encountering.

**Comment by jourdain** [comment]
Did you just do the following? And on which system?

```bash
conda create --name xaitk python=3.9 -y
conda activate xaitk
pip install -e .

# And then the following worked?
xaitk-saliency-demo
```

I guess my question is double:

1. Which versions should we be using today a year later or so. (python 3.10? version of various packages?)
2. What would be the recommended setup to get things working? (i.e. conda install vs pip install...)

**Comment by Purg** [comment]
Ah, I wasn't sure if your error was on the installation or the running, I didn't clearly run the demo app. That's my fault. Is the issue you are having a `SystemError: initialization of _internal failed without raising an exception`?

**Comment by Purg** [comment]
Ah, yes, `numba`. We have an active ticket address that numba is not being correctly specified by `smqtk-detection`.

**Comment by jourdain** [comment]
Yes on my linux that is the error I get.

For the mac, the error happen at `pip install ...` but somehow I was expecting that.
I think I managed to get it working when I was actually using conda to install some of those dependencies ahead of time.

**Comment by brianhhu** [comment]
Hi @jourdain, thanks for your work on updating the `xaitk-saliency-web-demo` app- I feel a lot of the other issues are blocked by getting the dependency update correct (which we are working on now), since you cannot test changes locally. I'll ping you when this gets resolved, but hopefully it will be soon. Thanks!

**Comment by jourdain** [comment]
yes indeed. Also what I've done so far was just the easy part that I could move forward without having things running.

**Comment by brianhhu** [comment]
Hi @jourdain @Purg, I believe @bjrichardwebster has just [pushed a new minor release](https://github.com/XAITK/xaitk-saliency/releases) of `xaitk-saliency` which makes use of an updated version of `smqtk-detection`, as well as fixes some of our other dependency issues/warnings. Could you see if the latest version works to address this particular issue? Thanks

**Comment by jourdain** [comment]
I'll pick it up where I left off. But I'm traveling to KHQ this week.

**Comment by jourdain** [comment]
So I tried to update the dependencies and see if I was going through with my mac (M1) but I get the following error

```
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/Users/sebastien.jourdain/.pyenv/versions/3.9.9/lib/python3.9/site-packages/torch/ao/quantization/__init__.py)
```

This is what I have in term of versions, please let me know if I should pick another set. 

```
    trame>=2.1.0
    trame-components>=2.0.4
    plotly==5.15.0

    smqtk-classifier==0.19.0
    smqtk-core==0.19.0
    smqtk-dataprovider==0.18.0
    smqtk-descriptors==0.19.0
    smqtk-detection[torch,centernet]==0.20.0
    smqtk-image-io==0.17.1

    xaitk-saliency==0.7.0
    ubelt==1.3.2

    torchvision==0.14.1
    scikit-learn==1.3.0
    scikit-image==0.21.0
```

Tomorrow, I'll try on my linux.

**Comment by brianhhu** [comment]
@jourdain Paul is out on vacation this week. What version of `torch` are you on?

I think it might be a torch/torchvision version mismatch error: https://stackoverflow.com/questions/73420840/importerror-cannot-import-name-quantstub-from-torch-ao-quantization

Let us know what happens with Linux. Thanks!

**Comment by jourdain** [comment]
I think so too that is a torch/torchvision missmatch. Which version do you have that is working? That way I can fix them to make sure I don't run into such missmatch. So far I was just forcing `torchvision==0.14.1`

**Comment by jourdain** [comment]
On linux it went through without a glitch. I mean, I was missing a dependency but I'm good for now...

**Comment by jourdain** [comment]
Seems fine if we ignore mac-arm platform
