### ISSUE TITLE
Demo won't start `zsh: command not found: xaitk_saliency_demo`

### ISSUE THREAD

**Issue by ai2ys** [XAITK/xaitk-saliency-web-demo#7]
I followed the instructions of the ReadMe file, but after installing all prerequisites I get the following error, no matter if I use the PyPi package for installation or if I install it from the project directory.

```                
zsh: command not found: xaitk_saliency_demo
```

What is missing to run the demo?

**Comment by ai2ys** [comment]
Does work now after reinstalling everything.

**Comment by Purg** [comment]
I'm glad it is working now for you!
