### ISSUE TITLE
Update demo to use latest version of trame

### ISSUE THREAD

**Issue by brianhhu** [XAITK/xaitk-saliency-web-demo#9]
This issue addresses technical debt on the `xaitk-saliency-web-demo`, as it has not been updated recently. The latest version of `trame` and `xaitk-saliency` can be pulled in, and any dependency-related issues should either be addressed or noted for additional discussion.

**Comment by jourdain** [comment]
Latest version of trame can be pulled and should be compatible but it might be worth revisiting the app structure.
The ideal would be follow the latest best practice. 
We may want to use plotly as chart library instead of Altair/vega?

**Comment by brianhhu** [comment]
I am not very familiar with plotly vs. altair/vega differences, but in general supportive of bringing the app up-to-date with best practices. We should also reference #15 in terms of the other dependency updates required.

**Comment by jourdain** [comment]
It seems that plotly is the defacto standard chart library. The other works fine, but it could be good to move toward a single/common way of doing charts in trame. The initial phase was to try integrate as many libraries out there (since it was easy). Now we are more in a consolidating phase where we try to normalize how we do things... ;-)

**Comment by jourdain** [comment]
We are using the latest code base along with the switch to using plotly. 

In term of possible improvement we have the remaining paths:
- Refactor code base to use a class based approach to be more inline with latest trame structure.
- Migrate to vue3 on the client side but we are not fully ready for the various widgets that xaitk is using. 

But truly none of the listed point are needed if you are satisfied with the current code base.

**Comment by jourdain** [comment]
Latest version of trame... The remaining part will be to move to vue3 which will require to make trame-components compatible vue2 and vue3 (almost there) and use vuetify3. This may happen organically. Closing for now.
